### ISSUE TITLE
Limitation of single Jak game installation at a time with OpenGOAL 1.1.1 Decky Plugin

### ISSUE THREAD

**Issue by Plarpoon** [open-goal/decky-plugin#6]
I noticed an interesting scenario with my Steam Deck where I have both the ISOs for Jak 1 and Jak 2. However, when I attempt to install them using the decky loader plugin in OpenGOAL, it appears I can only install one game at a time. This is specifically the case when I use the shortcut maker. I can either have only one or the other. I’m not sure if this is by design or not, but I thought it was worth mentioning. I was hoping to have both games installed simultaneously. Any insights would be greatly appreciated.

**Comment by DaniRainbow** [comment]
I installed both games and created shortcuts for both games using 1.1.1 all I had to do was restart my steam deck every time it asked me to

**Comment by Plarpoon** [comment]
I did exactly that as-well but once the reboot was completed the previously created shortcut was gone and the new one was there.

Are there any logs I could provide perhaps?

**Comment by mattboy9921** [comment]
I also just ran into this issue. I just got everything set up for the first time with both Jak 1 and Jak 2. The solution I've found to get both to show is to open whichever shows and let the game load up for the first time. Then quit the game and create the shortcut for the other. Now both should show.
