### ISSUE TITLE
Change framerate

### ISSUE THREAD

**Issue by Frehgin** [open-goal/decky-plugin#8]
I installed Jak 1 on both my pc with the launcher and my steamdeck with the decky plugin and on the steamdeck I miss the experimental option to change de framerite, which is a shame considering the oled uses a 90hz display.
Is this normal or am I missing something?

**Comment by Zedb0T** [comment]
Normal, jak 1 engine only supports frames rates 300 is divisible by

**Comment by Frehgin** [comment]
I installed the game and launched it using a 60hz display, the option wasn't available then, unplugged the display, restarted the game, now it offers a 100fps option :)
